### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by llan-ml** [ivam-he/ChebNetII#1]
Hi @ivam-he ,
Recently, I saw your nice paper "Convolutional Neural Networks on Graphs with Chebyshev Approximation, Revisited", and would like to test it. Do you have an ETA to release the code? I am really looking forward to it. Thanks!

**Comment by ivam-he** [comment]
I apologize for the delay, and I will open the code before the end of the NeurIPS2022 conference (i.e., Before Dec 10).
