### ISSUE TITLE
figure1(b)中k=10时，为什么ChebBase/k点的位置不在ChebBase的十分之一处？

### ISSUE THREAD

**Issue by guanyipengai** [ivam-he/ChebNetII#2]

**Comment by ivam-he** [comment]
guanyipengai，你好，

$ChebBase/k$ 的系数是 $w_k/k$。在实现中是对每一个epoch前向传播时都对可学习的参数 $w_k$ 除以 $k$，而不是训练好了 $w_k$ 再除 以 $k$，所以 $ChebBase$ 和 $ChebBase/k$ 最后学到的 $w_k$ 不一样。也就是说， $ChebBase$ 和  $ChebBase/k$ 系数的应该是它们分别学到的 $w_k$ 和 $w_k/k$ ，因此在图上没有在十分之一处。

希望的我的回答对你有所帮助。

**Comment by guanyipengai** [comment]
感谢您的回复：

如您所说，ChebBase/k的训练过程中，前向传播公式是论文中的公式（6），其中k是常数,for k in 1,2,...,10。w_k是可训练参数。

我们记ChebBase训练得到的权重是w*，记ChebBase/k训练得到的权重为w#。
如果是这样，使用梯度下降算法如果损失函数收敛到同一点，最后应该会有w*=w#/k。

我做了实验也支持我的想法，我使用多项式生成了一组数据，真实的表达式是y=1+3x+5x^2+7x^3。
当我使用y=a+bx+cx^2+dx^3作为前向传播公式时，最后学习到的参数是：0.99，3.00，4.99，7.00
当我使用y=a+(bx)/1+(cx^2)/2+(dx^3)/3作为前向传播公式时，最后学习到的参数是：0.99，3.00，9.97，21.0
所以梯度下降算法是能够学习到前向传播公式中的系数变化。

基于此，我认为给前向传播公式乘以1/k这个系数，难以保证最后学习到的切比雪夫因数满足定理2.1描述的限制。

**Comment by ivam-he** [comment]
是的，你的分析是合理的。在假设ChebBase和ChebBase/k都能够收敛到同一点并且都是最优解的时候，w*=w#/k会成立。但是，在模型的实际训练中ChebBase和ChebBase/k可能不会收敛到同一点，而且还有受到MLP参数的影响，所以很难得到w*=w#/k的结果。另外，定理2.1主要是想告诉我们系数w需要渐近收敛，而从实验上看，ChebBase/k相对于ChebBase更容易满足这种收敛的趋势，也就是一般会有w*>w#/k。

总的来说，在转播过程中ChebBase/k只是在一定程度上可以满足定理2.1收敛的限制，我们也不认为它是一个好的方法，这也是我们使用Chebyshev Interpolation的动机之一。

**Comment by guanyipengai** [comment]
感谢您的回复，祝工作顺利，新年快乐！
